apiVersion: v1
kind: Service
metadata:
  labels:
    app: foo
  name: foo
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'
    anthos.cft.dev/autoneg: '{"name":"backend-service-foo", "max_rate_per_endpoint":10}'
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
    name: http
  selector:
    app: foo
